'''Configuration file for SHMU data processing'''

TOPDIR = r'/home/pp/program/jupyter/SHMU/zber/'
TEPLOTY_SK_DIR = TOPDIR + r'teploty_sk/'
ZRAZKY_BREZNO_DIR = TOPDIR + r'zrazky_brezno/'
ZRAZKY_SK_DIR = TOPDIR + r'zrazky_sk/'
HLADINY_SK_DIR = TOPDIR + r'hladiny_sk/'
PRIETOKY_SK_DIR = TOPDIR + r'prietoky_sk/'
TEMPTESTFILE = TEPLOTY_SK_DIR + '2025-07-30-15-00.html'
UHRNTESTFILE = ZRAZKY_BREZNO_DIR + '2025-07-30-23-45.html'